// demo/vue/format-me-vue.vue
<script setup>
// Mis-formatted on purpose. Run "Format code file".
import {ref,computed} from "vue";
const name=ref("Ada");const roles=ref(["admin","editor"]);
const isAdmin=computed(()=>roles.value.includes("admin"));
function addRole(role){roles.value.push(role);}
</script>
<template>
<main class="card"><h1>{{ name }}</h1><span v-if="isAdmin" class="badge">Admin</span>
<ul><li v-for="role in roles" :key="role">{{ role }}</li></ul></main>
</template>
<style scoped>
.card{max-width:400px;margin:0 auto;}.badge{color:#0a84ff;}
</style>

// demo/svelte/format-me-svelte.svelte
<script>
  // Mis-formatted on purpose. Run "Format code file".
  let name="Ada";let roles=["admin","editor"];
  $: isAdmin=roles.includes("admin");
  $: summary=`${name} has ${roles.length} roles`;
  function addRole(role){roles=[...roles,role];}
</script>
<main class="card"><h1>{summary}</h1>{#if isAdmin}<span class="badge">Admin</span>{/if}
<ul>{#each roles as role}<li>{role}</li>{/each}</ul></main>
<style>.card{max-width:400px;margin:0 auto;}.badge{color:#0a84ff;}</style>
